update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,6 +24,23 @@ jobs:
       - name: Install dependencies
         run: npm install
 
+            # Start server
+      - name: Start server
+        run: npm run tern-on-api &
+
+      # wait for server 
+      - name: Wait for server to start
+        run: |
+          for i in {1..10}; do
+            if nc -z localhost 3000; then
+              echo "Server is up!"
+              exit 0
+            fi
+            echo "Waiting for server to start..."
+            sleep 2
+          done
+          echo "Server failed to start" && exit 1
+
       # Install newman and reporter
       - name: Install newman
         run: |
